### ISSUE TITLE
Queztal Sign-up fail

### ISSUE THREAD

**Issue by VoidXpulse** [EpicGamer1YT/ProjectCrossComm#23]
**Describe the bug**
Signing up doesn't work
**To Reproduce**
1. Go to sign up
2. Fill in sign up
3. Click on sign up

**Expected behavior**
To get to the chat room

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

![queztalnotworking](https://user-images.githubusercontent.com/48094071/55556263-2026e500-56b5-11e9-995c-ae6e144e7ad2.PNG)

**Comment by tsquid** [comment]
same issue

**Comment by CAM-o-man** [comment]
The autolink on sign in had the incorrect URL. Now resolved.
