### ISSUE TITLE
email layering

### ISSUE THREAD

**Issue by tsquid** [EpicGamer1YT/ProjectCrossComm#25]
emails layer when searching for two users

**To Reproduce**
1. Go to chat
2. start a chat with an email
3. add another email

**Expected behavior**
it should be replaced, but it prints next to the original

**Screenshots**

**Desktop (please complete the following information):**
 - OS: PC
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by VoidXpulse** [comment]
![multiple emails](https://user-images.githubusercontent.com/48094071/55557033-f53d9080-56b6-11e9-84b8-9abb55ec9eaf.PNG)

**Comment by CAM-o-man** [comment]
This will be resolved with continued development, however I will leave the issue open for now.

**Comment by CAM-o-man** [comment]
Resolved.
