### ISSUE TITLE
Chatroom issues

### ISSUE THREAD

**Issue by tsquid** [EpicGamer1YT/ProjectCrossComm#26]
the chat tab only works from sign in page

**To Reproduce**
1. Go to any site other than the sign in
2. Click on chatroom
3. error 404

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CAM-o-man** [comment]
There's a capitalization error in the other rooms.

**Comment by CAM-o-man** [comment]
Resolved.
